In [1]:
import pandas as pd

In [ ]:
# removed hard-coded API key

In [5]:
pip install google-generativeai

Collecting google-generativeai
  Using cached google_generativeai-0.8.6-py3-none-any.whl.metadata (3.9 kB)
Collecting google-ai-generativelanguage==0.6.15 (from google-generativeai)
  Using cached google_ai_generativelanguage-0.6.15-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: google-api-core in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-generativeai) (2.30.2)
Requirement already satisfied: google-api-python-client in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-generativeai) (2.194.0)
Requirement already satisfied: google-auth>=2.15.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-generativeai) (2.48.0)
Requirement already satisfied: protobuf in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-generativeai) (5.29.5)
Requirement already satisfied: pydantic in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-generativeai) (2.11.7)
Requirement already satisfied: tqdm in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-generativeai) (4.66.5)
Requirement already satisfied: typing-extensions in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-generativeai) (4.14.1)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.27.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-api-core->google-generativeai) (1.72.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-api-core->google-generativeai) (2.32.5)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (46.0.3)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from pydantic->google-generativeai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from pydantic->google-generativeai) (0.4.1)
Requirement already satisfied: colorama in c:\users\king\appdata\roaming\python\python311\site-packages (from tqdm->google-generativeai) (0.4.6)
Requirement already satisfied: cffi>=2.0.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.0.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.80.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2025.7.14)
Requirement already satisfied: pycparser in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.22)
Using cached google_generativeai-0.8.6-py3-none-any.whl (155 kB)
Using cached google_ai_generativelanguage-0.6.15-py3-none-any.whl (1.3 MB)
Installing collected packages: google-ai-generativelanguage, google-generativeai
Successfully installed google-ai-generativelanguage-0.6.15 google-generativeai-0.8.6
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
pip install openai

Collecting openaiNote: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading openai-2.31.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from openai) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from openai) (0.28.1)
Collecting jiter<1,>=0.10.0 (from openai)
  Downloading jiter-0.13.0-cp311-cp311-win_amd64.whl.metadata (5.3 kB)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from openai) (2.11.7)
Requirement already satisfied: sniffio in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from openai) (4.66.5)
Requirement already satisfied: typing-extensions<5,>=4.11 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from openai) (4.14.1)
Requirement already satisfied: idna>=2.8 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from anyio<5,>=3.5.0->openai) (2.10)
Requirement already satisfied: certifi in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from httpx<1,>=0.23.0->openai) (2025.7.14)
Requirement already satisfied: httpcore==1.* in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)
Requirement already satisfied: colorama in c:\users\king\appdata\roaming\python\python311\site-packages (from tqdm>4->openai) (0.4.6)
Downloading openai-2.31.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.2 MB ? eta -:--:--
   --------- ------------------------------ 0.3/1.2 MB ? eta -:--:--
   ------------------ --------------------- 0.5/1.2 MB 578.7 kB/s eta 0:00:02
   ------------------ --------------------- 0.5/1.2 MB 578.7 kB/s eta 0:00:02
   --------------------------- ------------ 0.8/1.2 MB 699.0 kB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 781.2 kB/s eta 0:00:00
Downloading jiter-0.13.0-cp311-cp311-win_amd64.whl (204 kB)
Installing collected packages: jiter, openai
Successfully installed jiter-0.13.0 openai-2.31.0

In [ ]:
# removed hard-coded API key

In [2]:
data=pd.read_csv(r"C:\Users\King\Downloads\STEAM_GAMES.CSV")
data

,Unnamed: 0,game_name,app_id,review_text,review_length,hours_played,review_date,owners,developers,publishers,genres,platforms,categories,release_date,price
0,0,Counter-Strike: Global Offensive,730,pucajjj bam bam,15,197.216667,2026-03-02 01:55:35,"100,000,000 .. 200,000,000",['Valve'],['Valve'],"['Action', 'Free To Play']","['windows', 'linux']","['Multi-player', 'Cross-Platform Multiplayer',...","Aug 21, 2012",NaN
1,1,Counter-Strike: Global Offensive,730,YES,3,22.850000,2026-03-02 01:39:35,"100,000,000 .. 200,000,000",['Valve'],['Valve'],"['Action', 'Free To Play']","['windows', 'linux']","['Multi-player', 'Cross-Platform Multiplayer',...","Aug 21, 2012",NaN
2,2,Counter-Strike: Global Offensive,730,its pretty fun,14,24.150000,2026-03-02 01:32:54,"100,000,000 .. 200,000,000",['Valve'],['Valve'],"['Action', 'Free To Play']","['windows', 'linux']","['Multi-player', 'Cross-Platform Multiplayer',...","Aug 21, 2012",NaN
3,3,Counter-Strike: Global Offensive,730,awsone,6,264.666667,2026-03-02 01:30:30,"100,000,000 .. 200,000,000",['Valve'],['Valve'],"['Action', 'Free To Play']","['windows', 'linux']","['Multi-player', 'Cross-Platform Multiplayer',...","Aug 21, 2012",NaN
4,4,Counter-Strike: Global Offensive,730,s,1,136.316667,2026-03-02 01:30:21,"100,000,000 .. 200,000,000",['Valve'],['Valve'],"['Action', 'Free To Play']","['windows', 'linux']","['Multi-player', 'Cross-Platform Multiplayer',...","Aug 21, 2012",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,Wallpaper Engine,431960,Simply goated,13,3.616667,2026-02-28 21:36:51,"20,000,000 .. 50,000,000",['Wallpaper Engine Team'],['Wallpaper Engine Team'],"['Casual', 'Indie', 'Animation & Modeling', 'D...",['windows'],"['Steam Achievements', 'Steam Trading Cards', ...","Nov 16, 2018",499.0
1996,1996,Wallpaper Engine,431960,"""it cool""",9,0.183333,2026-02-28 21:30:32,"20,000,000 .. 50,000,000",['Wallpaper Engine Team'],['Wallpaper Engine Team'],"['Casual', 'Indie', 'Animation & Modeling', 'D...",['windows'],"['Steam Achievements', 'Steam Trading Cards', ...","Nov 16, 2018",499.0
1997,1997,Wallpaper Engine,431960,good\r\n,6,3.600000,2026-02-28 21:15:45,"20,000,000 .. 50,000,000",['Wallpaper Engine Team'],['Wallpaper Engine Team'],"['Casual', 'Indie', 'Animation & Modeling', 'D...",['windows'],"['Steam Achievements', 'Steam Trading Cards', ...","Nov 16, 2018",499.0
1998,1998,Wallpaper Engine,431960,i like cat,10,59.416667,2026-02-28 20:38:56,"20,000,000 .. 50,000,000",['Wallpaper Engine Team'],['Wallpaper Engine Team'],"['Casual', 'Indie', 'Animation & Modeling', 'D...",['windows'],"['Steam Achievements', 'Steam Trading Cards', ...","Nov 16, 2018",499.0
1999,1999,Wallpaper Engine,431960,good,4,24.166667,2026-02-28 20:35:11,"20,000,000 .. 50,000,000",['Wallpaper Engine Team'],['Wallpaper Engine Team'],"['Casual', 'Indie', 'Animation & Modeling', 'D...",['windows'],"['Steam Achievements', 'Steam Trading Cards', ...","Nov 16, 2018",499.0

In [ ]:
sample_df = data.sample(200, random_state=42).copy()

In [ ]:
from openai import OpenAI
import os
import pandas as pd
import time
from tqdm import tqdm

tqdm.pandas()

client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY", ""),
    base_url="https://api.groq.com/openai/v1"
)

sample_df = data.sample(200, random_state=42).copy()

def get_sentiment_groq(text):
    prompt = f"""
You are a highly strict sentiment annotator for Steam game reviews.

Your job is classification into ONLY 3 labels:
positive, negative, neutral

-------------------------
CRITICAL RULES:
-------------------------
1. NEVER default to neutral.
2. neutral is ONLY for completely meaningless text OR no opinion at all.
3. If ANY sentiment hint exists → choose positive or negative.
4. gaming slang MUST be interpreted:
   - fun, enjoyable, addictive, amazing, good, great, insane, love → positive
   - lag, bug, crash, broken, trash, unplayable, pay-to-win → negative

5. SHORT TEXT RULE:
   If text is short (<= 5 words), STILL try to infer sentiment.

6. OUTPUT RULE:
   Return ONLY one word:
   positive OR negative OR neutral

-------------------------
EXAMPLES:
-------------------------
"this game is fun" → positive
"full of bugs" → negative
"engine" → neutral
"i love it" → positive
"trash game" → negative

-------------------------
REVIEW:
{text}
"""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "user", "content": prompt}
            ],
            temperature=0
        )

        time.sleep(0.5)
        return response.choices[0].message.content.strip().lower()

    except Exception as e:
        return "neutral"

In [ ]:
from openai import OpenAI
import os
import pandas as pd
import time
from tqdm import tqdm

tqdm.pandas()

# =========================
# GROQ CLIENT
# =========================
client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY", ""),
    base_url="https://api.groq.com/openai/v1"
)

# =========================
# SAMPLE DATA
# =========================
sample_df = data.sample(200, random_state=42).copy()

# =========================
# STRONG SENTIMENT PROMPT
# =========================
def get_sentiment_groq(text):

    prompt = f"""
You are a sentiment annotation system for Steam game reviews.

You MUST classify sentiment into exactly ONE label:

LABELS:
- positive
- negative
- neutral

========================
STRICT DECISION RULES:
========================

1. NEVER default to neutral.
2. neutral is ONLY for:
   - meaningless text (e.g. "engine", "ok", random words)
   - no opinion at all

3. If ANY emotion exists → MUST choose positive or negative.

4. Interpret gaming slang correctly:
   POSITIVE SIGNALS:
   fun, good, great, amazing, love, insane, addictive, enjoyable, awesome, nice

   NEGATIVE SIGNALS:
   lag, bug, crash, broken, trash, bad, boring, unplayable, pay-to-win, worst

5. Even VERY short text MUST be classified if possible.

6. If mixed sentiment exists → choose the dominant one.

========================
EXAMPLES:
========================
"this game is fun" → positive
"full of bugs and lag" → negative
"i love it" → positive
"trash game" → negative
"engine" → neutral
"not bad actually fun" → positive
"game is ok" → neutral

========================
REVIEW:
{text}
========================

Return ONLY one word:
positive OR negative OR neutral
"""

    try:
        response = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "user", "content": prompt}
            ],
            temperature=0,
            max_tokens=5
        )

        time.sleep(0.2)  # reduced delay for speed

        label = response.choices[0].message.content.strip().lower()

        # safety cleanup (very important)
        if "positive" in label:
            return "positive"
        elif "negative" in label:
            return "negative"
        elif "neutral" in label:
            return "neutral"
        else:
            return "neutral"

    except Exception as e:
        print("Error:", e)
        return "neutral"


# =========================
# APPLY WITH PROGRESS BAR
# =========================
sample_df["label_1"] = sample_df["review_text"].astype(str).progress_apply(get_sentiment_groq)

# =========================
# CHECK DISTRIBUTION
# =========================
print(sample_df["label_1"].value_counts())
sample_df.head()

  0%|          | 0/200 [00:00<?, ?it/s]

100%|██████████| 200/200 [10:17<00:00,  3.09s/it]

label_1
positive    107
negative     63
neutral      30
Name: count, dtype: int64

,Unnamed: 0,game_name,app_id,review_text,review_length,hours_played,review_date,owners,developers,publishers,genres,platforms,categories,release_date,price,label_1
1860,1860,Path of Exile 2,2694490,`,1,10.600000,2026-02-26 23:50:27,"20,000,000 .. 50,000,000",['Grinding Gear Games'],['Grinding Gear Games'],"['Action', 'Adventure', 'Massively Multiplayer...",['windows'],"['Single-player', 'Multi-player', 'MMO', 'Co-o...","Dec 6, 2024",2999.0,neutral
353,353,Palworld,1623730,incredibly fun and great replayability (i thin...,79,92.016667,2026-02-28 14:33:41,"50,000,000 .. 100,000,000",['Pocketpair'],['Pocketpair'],"['Action', 'Adventure', 'Indie', 'RPG', 'Early...",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Jan 18, 2024",2999.0,positive
1333,1333,Monster Hunter Wilds,2246340,I Monster my Hunter till I Wilds,32,113.883333,2026-03-01 10:51:44,"20,000,000 .. 50,000,000","['CAPCOM Co., Ltd.']","['CAPCOM Co., Ltd.']","['Action', 'Adventure', 'RPG']",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Feb 27, 2025",6999.0,negative
905,905,Left 4 Dead 2,550,This is a really good game if you love Zombie ...,74,33.550000,2026-03-01 23:18:17,"50,000,000 .. 100,000,000",['Valve'],['Valve'],['Action'],"['windows', 'linux']","['Single-player', 'Multi-player', 'PvP', 'Onli...","Nov 16, 2009",999.0,positive
1289,1289,War Thunder,236390,love the game but it pisses me the ♥♥♥♥ off un...,65,224.633333,2024-01-15 07:27:11,"20,000,000 .. 50,000,000",['Gaijin Entertainment'],['Gaijin Network Ltd'],"['Action', 'Massively Multiplayer', 'Simulatio...","['windows', 'mac', 'linux']","['Single-player', 'Multi-player', 'MMO', 'PvP'...","Aug 15, 2013",NaN,negative

In [19]:
sample_df

,Unnamed: 0,game_name,app_id,review_text,review_length,hours_played,review_date,owners,developers,publishers,genres,platforms,categories,release_date,price,label_1
1860,1860,Path of Exile 2,2694490,`,1,10.600000,2026-02-26 23:50:27,"20,000,000 .. 50,000,000",['Grinding Gear Games'],['Grinding Gear Games'],"['Action', 'Adventure', 'Massively Multiplayer...",['windows'],"['Single-player', 'Multi-player', 'MMO', 'Co-o...","Dec 6, 2024",2999.0,neutral
353,353,Palworld,1623730,incredibly fun and great replayability (i thin...,79,92.016667,2026-02-28 14:33:41,"50,000,000 .. 100,000,000",['Pocketpair'],['Pocketpair'],"['Action', 'Adventure', 'Indie', 'RPG', 'Early...",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Jan 18, 2024",2999.0,positive
1333,1333,Monster Hunter Wilds,2246340,I Monster my Hunter till I Wilds,32,113.883333,2026-03-01 10:51:44,"20,000,000 .. 50,000,000","['CAPCOM Co., Ltd.']","['CAPCOM Co., Ltd.']","['Action', 'Adventure', 'RPG']",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Feb 27, 2025",6999.0,neutral
905,905,Left 4 Dead 2,550,This is a really good game if you love Zombie ...,74,33.550000,2026-03-01 23:18:17,"50,000,000 .. 100,000,000",['Valve'],['Valve'],['Action'],"['windows', 'linux']","['Single-player', 'Multi-player', 'PvP', 'Onli...","Nov 16, 2009",999.0,positive
1289,1289,War Thunder,236390,love the game but it pisses me the ♥♥♥♥ off un...,65,224.633333,2024-01-15 07:27:11,"20,000,000 .. 50,000,000",['Gaijin Entertainment'],['Gaijin Network Ltd'],"['Action', 'Massively Multiplayer', 'Simulatio...","['windows', 'mac', 'linux']","['Single-player', 'Multi-player', 'MMO', 'PvP'...","Aug 15, 2013",NaN,negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,462,Team Fortress 2,440,the OG. The big chunga. This was one of the bi...,94,103.883333,2026-02-20 16:00:58,"50,000,000 .. 100,000,000",['Valve'],['Valve'],"['Action', 'Free To Play']","['windows', 'linux']","['Multi-player', 'Cross-Platform Multiplayer',...","Oct 10, 2007",NaN,positive
1105,1105,Lost Ark,1599340,I'm so grateful I quit playing in June of 2022...,319,924.116667,2026-02-22 04:17:29,"50,000,000 .. 100,000,000",['Smilegate RPG'],['Amazon Game Studios'],"['Action', 'Adventure', 'Massively Multiplayer...",['windows'],"['Single-player', 'Multi-player', 'MMO', 'PvP'...","Feb 11, 2022",NaN,negative
855,855,Grand Theft Auto V Legacy,271590,best game,9,31.683333,2026-03-01 07:10:12,"50,000,000 .. 100,000,000",['Rockstar North'],['Rockstar Games'],"['Action', 'Adventure']",['windows'],"['Single-player', 'Multi-player', 'PvP', 'Onli...","Apr 13, 2015",NaN,positive
693,693,New World: Aeternum,1063730,I started a few times over since the story cha...,592,1342.783333,2026-02-08 09:09:30,"50,000,000 .. 100,000,000",['Amazon Game Studios'],['Amazon Game Studios'],"['Action', 'Adventure', 'Massively Multiplayer...",['windows'],"['Multi-player', 'MMO', 'PvP', 'Online PvP', '...","Sep 28, 2021",NaN,negative
1551,1551,Warframe,230410,"at the very end, when i stop playing any and a...",96,2656.066667,2023-12-03 17:33:24,"20,000,000 .. 50,000,000",['Digital Extremes'],['Digital Extremes'],"['Action', 'RPG', 'Free To Play']",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Mar 25, 2013",NaN,positive

In [18]:
data["review_text"].loc[905]

'This is a really good game if you love Zombie Apocolypse games! Good luck,'

In [70]:
sample_df["label_1"].value_counts()

label_1
positive    107
negative     63
neutral      30
Name: count, dtype: int64

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [71]:
sample_df[sample_df["label_1"]=="negative"]["review_text"].to_frame()

                                            review_text
1333                   I Monster my Hunter till I Wilds
1289  love the game but it pisses me the ♥♥♥♥ off un...
56                                 valve pls anti cheat
584                                            cod slop
1852  LOOOOVVVVEEEEEDDDDDDDD POE1!! \n\nBut man this...
...                                                 ...
1990                                    i dont like men
1190  amazon sucks for man reason including this ces...
602   Game is dead now, but the leveling felt good, ...
1105  I'm so grateful I quit playing in June of 2022...
693   I started a few times over since the story cha...

[63 rows x 1 columns]

In [72]:
sample_df[sample_df["label_1"]=="positive"]["review_text"].to_frame()

                                            review_text
353   incredibly fun and great replayability (i thin...
905   This is a really good game if you love Zombie ...
1273                                          game good
938   Best game to play with a full group and stacke...
65                                       WERY GOOD GSME
...                                                 ...
1225   Leaking documents is fun 10000/10 would do again
1384  So far the best Monster Hunter Experience for ...
462   the OG. The big chunga. This was one of the bi...
855                                           best game
1551  at the very end, when i stop playing any and a...

[107 rows x 1 columns]

In [ ]:
# removed hard-coded API key

In [3]:
from openai import OpenAI
import os
import pandas as pd
import time
from tqdm import tqdm

tqdm.pandas()

# ===============================
# OpenRouter Client
# ===============================
client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY", ""),
    base_url="https://openrouter.ai/api/v1"
)

MODEL_NAME = "openrouter/free"

# sample 200
sample_df = data.sample(200, random_state=42).copy()

def get_sentiment(text):
    prompt = f"""
You are an expert sentiment classifier for Steam game reviews.

Gaming sentiment rules:
- fun, amazing, replayability, addictive = positive
- lag, bug, crash, trash, pay-to-win = negative
- neutral ONLY if no opinion exists

IMPORTANT:
Do NOT overuse neutral.
Always choose positive or negative if sentiment exists.

Review:
{text}

Return ONLY one word:
positive, negative, or neutral
"""

    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "user", "content": prompt}
            ],
            temperature=0,
            max_tokens=5
        )

        time.sleep(0.3)
        return response.choices[0].message.content.strip().lower()

    except Exception as e:
        print("Error:", e)
        return "neutral"

sample_df["label_2"] = (
    sample_df["review_text"]
    .astype(str)
    .progress_apply(get_sentiment)
)

print(sample_df["label_2"].value_counts())
sample_df.head()

  1%|          | 2/200 [00:03<05:39,  1.72s/it]

Error: 'NoneType' object has no attribute 'strip'

  2%|▏         | 4/200 [00:14<13:11,  4.04s/it]

Error: 'NoneType' object has no attribute 'strip'

  4%|▎         | 7/200 [00:23<10:36,  3.30s/it]

Error: 'NoneType' object has no attribute 'strip'

  4%|▍         | 9/200 [00:33<11:59,  3.76s/it]

Error: 'NoneType' object has no attribute 'strip'

  6%|▌         | 12/200 [00:38<07:18,  2.33s/it]

Error: Error code: 404 - {'error': {'message': 'Provider returned error', 'code': 404, 'metadata': {'raw': '404 page not found\n', 'provider_name': 'Nvidia', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

  6%|▋         | 13/200 [00:42<09:17,  2.98s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  7%|▋         | 14/200 [00:48<11:30,  3.71s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  8%|▊         | 15/200 [00:53<12:30,  4.05s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  8%|▊         | 16/200 [00:58<13:23,  4.37s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.2-3b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 10%|▉         | 19/200 [01:12<13:53,  4.61s/it]

Error: 'NoneType' object has no attribute 'strip'

 10%|█         | 20/200 [01:14<11:32,  3.85s/it]

Error: 'NoneType' object has no attribute 'strip'

 10%|█         | 21/200 [01:18<11:39,  3.91s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'google/gemma-3-12b-it:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Google AI Studio', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 12%|█▏        | 24/200 [01:41<21:18,  7.27s/it]

Error: 'NoneType' object has no attribute 'strip'

 13%|█▎        | 26/200 [01:45<13:16,  4.58s/it]

Error: 'NoneType' object has no attribute 'strip'

 14%|█▍        | 28/200 [01:50<10:53,  3.80s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'nousresearch/hermes-3-llama-3.1-405b:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 16%|█▌        | 31/200 [02:02<10:02,  3.57s/it]

Error: 'NoneType' object has no attribute 'strip'

 16%|█▌        | 32/200 [02:07<11:11,  4.00s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'google/gemma-3-27b-it:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Google AI Studio', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 16%|█▋        | 33/200 [02:11<10:56,  3.93s/it]

Error: 'NoneType' object has no attribute 'strip'

 18%|█▊        | 37/200 [02:31<15:12,  5.60s/it]

Error: 'NoneType' object has no attribute 'strip'

 20%|█▉        | 39/200 [02:43<15:08,  5.64s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828880000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 20%|██        | 41/200 [02:48<10:41,  4.03s/it]

Error: 'NoneType' object has no attribute 'strip'

 22%|██▏       | 44/200 [03:01<11:40,  4.49s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828880000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 22%|██▎       | 45/200 [03:02<09:04,  3.52s/it]

Error: 'NoneType' object has no attribute 'strip'

 23%|██▎       | 46/200 [03:06<09:14,  3.60s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 24%|██▎       | 47/200 [03:10<09:43,  3.81s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'qwen/qwen3-next-80b-a3b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 24%|██▍       | 48/200 [03:14<09:20,  3.69s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 24%|██▍       | 49/200 [03:18<09:23,  3.73s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 25%|██▌       | 50/200 [03:23<10:17,  4.11s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 26%|██▌       | 51/200 [03:27<10:31,  4.24s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 26%|██▌       | 52/200 [03:32<10:45,  4.36s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 26%|██▋       | 53/200 [03:36<10:15,  4.18s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 27%|██▋       | 54/200 [03:39<09:25,  3.87s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 28%|██▊       | 55/200 [03:43<09:36,  3.97s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.2-3b-instruct/e8440b11-29fb-4887-a222-eff9ba33dfbf. High demand for meta-llama/llama-3.2-3b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 28%|██▊       | 56/200 [03:46<08:56,  3.73s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 28%|██▊       | 57/200 [03:50<08:50,  3.71s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 29%|██▉       | 58/200 [03:53<08:45,  3.70s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 30%|██▉       | 59/200 [03:57<08:47,  3.74s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 30%|███       | 60/200 [04:00<08:22,  3.59s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775828940000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 30%|███       | 61/200 [04:04<08:29,  3.67s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 31%|███       | 62/200 [04:09<09:23,  4.09s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.2-3b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 32%|███▏      | 63/200 [04:14<09:38,  4.22s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 32%|███▏      | 64/200 [04:17<08:40,  3.83s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 32%|███▎      | 65/200 [04:21<09:02,  4.02s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 33%|███▎      | 66/200 [04:26<09:32,  4.27s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 34%|███▎      | 67/200 [04:30<09:05,  4.10s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 34%|███▍      | 68/200 [04:34<08:46,  3.99s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 34%|███▍      | 69/200 [04:38<08:47,  4.02s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 35%|███▌      | 70/200 [04:43<09:15,  4.27s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/venice/uncensored/2d9e49f9-2147-4259-9871-4f6b6f181976. High demand for cognitivecomputations/dolphin-mistral-24b-venice-edition:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 36%|███▌      | 71/200 [04:47<09:09,  4.26s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 36%|███▌      | 72/200 [04:51<09:04,  4.25s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 36%|███▋      | 73/200 [04:54<08:22,  3.96s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 37%|███▋      | 74/200 [04:58<08:23,  4.00s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/venice/uncensored/2d9e49f9-2147-4259-9871-4f6b6f181976. High demand for cognitivecomputations/dolphin-mistral-24b-venice-edition:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829000000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 38%|███▊      | 75/200 [05:02<08:21,  4.01s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'cognitivecomputations/dolphin-mistral-24b-venice-edition:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 38%|███▊      | 76/200 [05:07<08:47,  4.26s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 38%|███▊      | 77/200 [05:12<09:08,  4.46s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.2-3b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 39%|███▉      | 78/200 [05:17<09:23,  4.62s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829060000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 40%|███▉      | 79/200 [05:22<09:23,  4.66s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 40%|████      | 80/200 [05:26<08:50,  4.42s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 40%|████      | 81/200 [05:30<08:38,  4.36s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829060000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 41%|████      | 82/200 [05:34<08:09,  4.14s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/qwen/qwen3-next-80b-a3b-instruct-2509/94248808-ba97-4e3c-be60-1cb0928db51d. High demand for qwen/qwen3-next-80b-a3b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829060000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 42%|████▏     | 83/200 [05:39<08:51,  4.54s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829060000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 42%|████▏     | 84/200 [05:44<08:54,  4.61s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 42%|████▎     | 85/200 [05:47<08:14,  4.30s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 43%|████▎     | 86/200 [05:51<07:34,  3.99s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829060000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 44%|████▎     | 87/200 [05:54<07:15,  3.86s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829060000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 44%|████▍     | 88/200 [05:59<07:39,  4.10s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/venice/uncensored/2d9e49f9-2147-4259-9871-4f6b6f181976. High demand for cognitivecomputations/dolphin-mistral-24b-venice-edition:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829060000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 44%|████▍     | 89/200 [06:03<07:47,  4.21s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829120000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 45%|████▌     | 90/200 [06:07<07:33,  4.12s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829120000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 46%|████▌     | 91/200 [06:10<06:34,  3.62s/it]

Error: Error code: 402 - {'error': {'message': 'Provider returned error', 'code': 402, 'metadata': {'raw': '{"error":"API key USD spend limit exceeded. Your account may still have USD balance, but this API key has reached its configured USD spending limit."}', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 46%|████▌     | 92/200 [06:13<06:03,  3.37s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829120000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 46%|████▋     | 93/200 [06:17<06:51,  3.84s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 47%|████▋     | 94/200 [06:23<07:25,  4.20s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 48%|████▊     | 95/200 [06:26<07:03,  4.03s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.2-3b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 48%|████▊     | 96/200 [06:31<07:32,  4.36s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 48%|████▊     | 97/200 [06:35<07:09,  4.17s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 49%|████▉     | 98/200 [06:38<06:43,  3.96s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829120000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 50%|████▉     | 99/200 [06:42<06:31,  3.88s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829120000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 50%|█████     | 100/200 [06:46<06:20,  3.80s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.2-3b-instruct/e8440b11-29fb-4887-a222-eff9ba33dfbf. High demand for meta-llama/llama-3.2-3b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829120000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 50%|█████     | 101/200 [06:49<06:11,  3.75s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829120000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 51%|█████     | 102/200 [06:53<05:50,  3.58s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.2-3b-instruct/e8440b11-29fb-4887-a222-eff9ba33dfbf. High demand for meta-llama/llama-3.2-3b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829120000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 52%|█████▏    | 103/200 [06:56<05:34,  3.45s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 52%|█████▏    | 104/200 [07:01<06:31,  4.08s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829120000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 52%|█████▎    | 105/200 [07:05<06:18,  3.98s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 53%|█████▎    | 106/200 [07:09<06:02,  3.86s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 54%|█████▎    | 107/200 [07:12<05:49,  3.75s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 54%|█████▍    | 108/200 [07:16<05:37,  3.67s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 55%|█████▍    | 109/200 [07:20<05:41,  3.75s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 55%|█████▌    | 110/200 [07:23<05:31,  3.68s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 56%|█████▌    | 111/200 [07:27<05:38,  3.81s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 56%|█████▌    | 112/200 [07:31<05:45,  3.93s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 56%|█████▋    | 113/200 [07:35<05:31,  3.81s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 57%|█████▋    | 114/200 [07:38<05:13,  3.65s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/qwen/qwen3-next-80b-a3b-instruct-2509/94248808-ba97-4e3c-be60-1cb0928db51d. High demand for qwen/qwen3-next-80b-a3b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 57%|█████▊    | 115/200 [07:39<03:57,  2.79s/it]

Error: Error code: 402 - {'error': {'message': 'Provider returned error', 'code': 402, 'metadata': {'raw': '{"error":"API key USD spend limit exceeded. Your account may still have USD balance, but this API key has reached its configured USD spending limit."}', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 58%|█████▊    | 116/200 [07:44<04:53,  3.49s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 58%|█████▊    | 117/200 [07:47<04:37,  3.34s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 59%|█████▉    | 118/200 [07:50<04:27,  3.26s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/qwen/qwen3-coder-480b-a35b-07-25/a9bbd882-011f-4606-8f60-85f3cb642586. High demand for qwen/qwen3-coder:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 60%|█████▉    | 119/200 [07:53<04:16,  3.17s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 60%|██████    | 120/200 [07:57<04:20,  3.26s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829180000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 60%|██████    | 121/200 [07:59<04:06,  3.12s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 61%|██████    | 122/200 [08:04<04:30,  3.47s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 62%|██████▏   | 123/200 [08:08<04:50,  3.78s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.2-3b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 62%|██████▏   | 124/200 [08:13<05:17,  4.17s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 62%|██████▎   | 125/200 [08:17<05:09,  4.13s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 63%|██████▎   | 126/200 [08:21<04:58,  4.04s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 64%|██████▎   | 127/200 [08:25<04:49,  3.97s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 64%|██████▍   | 128/200 [08:29<04:41,  3.90s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 64%|██████▍   | 129/200 [08:32<04:22,  3.70s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 65%|██████▌   | 130/200 [08:35<04:06,  3.52s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 66%|██████▌   | 131/200 [08:38<03:53,  3.38s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 66%|██████▌   | 132/200 [08:42<03:56,  3.49s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 66%|██████▋   | 133/200 [08:46<04:07,  3.70s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 67%|██████▋   | 134/200 [08:49<03:46,  3.44s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 68%|██████▊   | 135/200 [08:52<03:37,  3.34s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 68%|██████▊   | 136/200 [08:55<03:27,  3.24s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 68%|██████▊   | 137/200 [08:58<03:18,  3.15s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 69%|██████▉   | 138/200 [09:02<03:28,  3.36s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829240000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 70%|██████▉   | 139/200 [09:06<03:34,  3.51s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'nousresearch/hermes-3-llama-3.1-405b:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 70%|███████   | 140/200 [09:10<03:54,  3.90s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'nousresearch/hermes-3-llama-3.1-405b:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 70%|███████   | 141/200 [09:16<04:20,  4.42s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 71%|███████   | 142/200 [09:20<04:07,  4.26s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 72%|███████▏  | 143/200 [09:25<04:16,  4.50s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 72%|███████▏  | 144/200 [09:31<04:31,  4.86s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 72%|███████▎  | 145/200 [09:35<04:16,  4.67s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 73%|███████▎  | 146/200 [09:38<03:46,  4.19s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 74%|███████▎  | 147/200 [09:42<03:34,  4.04s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 74%|███████▍  | 148/200 [09:45<03:19,  3.84s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 74%|███████▍  | 149/200 [09:49<03:11,  3.75s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 75%|███████▌  | 150/200 [09:53<03:20,  4.02s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 76%|███████▌  | 151/200 [09:57<03:09,  3.88s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829300000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 76%|███████▌  | 152/200 [10:00<03:03,  3.81s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 76%|███████▋  | 153/200 [10:06<03:22,  4.30s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'cognitivecomputations/dolphin-mistral-24b-venice-edition:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 77%|███████▋  | 154/200 [10:12<03:38,  4.76s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 78%|███████▊  | 155/200 [10:16<03:31,  4.71s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 78%|███████▊  | 156/200 [10:20<03:13,  4.39s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 78%|███████▊  | 157/200 [10:24<02:59,  4.19s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 79%|███████▉  | 158/200 [10:27<02:42,  3.87s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 80%|███████▉  | 159/200 [10:31<02:37,  3.84s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 80%|████████  | 160/200 [10:34<02:33,  3.83s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/venice/uncensored/2d9e49f9-2147-4259-9871-4f6b6f181976. High demand for cognitivecomputations/dolphin-mistral-24b-venice-edition:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 80%|████████  | 161/200 [10:38<02:26,  3.75s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'qwen/qwen3-next-80b-a3b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 81%|████████  | 162/200 [10:41<02:18,  3.65s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 82%|████████▏ | 163/200 [10:46<02:21,  3.82s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 82%|████████▏ | 164/200 [10:49<02:11,  3.66s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 82%|████████▎ | 165/200 [10:52<02:02,  3.50s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 83%|████████▎ | 166/200 [10:56<02:08,  3.78s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 84%|████████▎ | 167/200 [11:00<02:06,  3.83s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829360000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 84%|████████▍ | 168/200 [11:04<02:02,  3.83s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829420000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 84%|████████▍ | 169/200 [11:09<02:09,  4.18s/it]

Error: Error code: 402 - {'error': {'message': 'Provider returned error', 'code': 402, 'metadata': {'raw': '{"error":"API key USD spend limit exceeded. Your account may still have USD balance, but this API key has reached its configured USD spending limit."}', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 85%|████████▌ | 170/200 [11:15<02:22,  4.73s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 86%|████████▌ | 171/200 [11:21<02:23,  4.94s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829420000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 86%|████████▌ | 172/200 [11:25<02:15,  4.83s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829420000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 86%|████████▋ | 173/200 [11:29<02:04,  4.59s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'qwen/qwen3-next-80b-a3b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 87%|████████▋ | 174/200 [11:33<01:52,  4.31s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829420000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 88%|████████▊ | 175/200 [11:37<01:42,  4.11s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829420000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 88%|████████▊ | 176/200 [11:40<01:31,  3.80s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829420000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 88%|████████▊ | 177/200 [11:44<01:27,  3.82s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829420000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 89%|████████▉ | 178/200 [11:48<01:25,  3.88s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 90%|████████▉ | 179/200 [11:52<01:27,  4.18s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 90%|█████████ | 180/200 [11:55<01:16,  3.83s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 90%|█████████ | 181/200 [11:59<01:11,  3.78s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 91%|█████████ | 182/200 [12:02<01:05,  3.61s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 92%|█████████▏| 183/200 [12:09<01:16,  4.51s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 92%|█████████▏| 184/200 [12:13<01:09,  4.33s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 92%|█████████▎| 185/200 [12:18<01:08,  4.58s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'cognitivecomputations/dolphin-mistral-24b-venice-edition:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 93%|█████████▎| 186/200 [12:22<01:00,  4.32s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 94%|█████████▎| 187/200 [12:25<00:52,  4.03s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 94%|█████████▍| 188/200 [12:29<00:46,  3.90s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 94%|█████████▍| 189/200 [12:33<00:44,  4.03s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 95%|█████████▌| 190/200 [12:36<00:37,  3.77s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.2-3b-instruct/e8440b11-29fb-4887-a222-eff9ba33dfbf. High demand for meta-llama/llama-3.2-3b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 96%|█████████▌| 191/200 [12:39<00:32,  3.60s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 96%|█████████▌| 192/200 [12:42<00:26,  3.37s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 96%|█████████▋| 193/200 [12:47<00:26,  3.85s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 97%|█████████▋| 194/200 [12:50<00:21,  3.66s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 98%|█████████▊| 195/200 [12:54<00:18,  3.60s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 98%|█████████▊| 196/200 [12:56<00:13,  3.28s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829480000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 98%|█████████▊| 197/200 [12:59<00:09,  3.20s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 99%|█████████▉| 198/200 [13:05<00:07,  3.90s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-min. ', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '16', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775829540000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

100%|█████████▉| 199/200 [13:11<00:04,  4.49s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

100%|██████████| 200/200 [13:16<00:00,  4.65s/it]

Error: Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'cognitivecomputations/dolphin-mistral-24b-venice-edition:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

100%|██████████| 200/200 [13:22<00:00,  4.01s/it]

Error: Error code: 429 - {'error': {'message': 'Rate limit exceeded: free-models-per-day. Add 10 credits to unlock 1000 free model requests per day', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '50', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775865600000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}
label_2
neutral                          181
positive                          12
negative                           4
we need to classify classify       1
we need to classify:               1
we need to classify sentiment      1
Name: count, dtype: int64

,Unnamed: 0,game_name,app_id,review_text,review_length,hours_played,review_date,owners,developers,publishers,genres,platforms,categories,release_date,price,label_2
1860,1860,Path of Exile 2,2694490,`,1,10.600000,2026-02-26 23:50:27,"20,000,000 .. 50,000,000",['Grinding Gear Games'],['Grinding Gear Games'],"['Action', 'Adventure', 'Massively Multiplayer...",['windows'],"['Single-player', 'Multi-player', 'MMO', 'Co-o...","Dec 6, 2024",2999.0,neutral
353,353,Palworld,1623730,incredibly fun and great replayability (i thin...,79,92.016667,2026-02-28 14:33:41,"50,000,000 .. 100,000,000",['Pocketpair'],['Pocketpair'],"['Action', 'Adventure', 'Indie', 'RPG', 'Early...",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Jan 18, 2024",2999.0,positive
1333,1333,Monster Hunter Wilds,2246340,I Monster my Hunter till I Wilds,32,113.883333,2026-03-01 10:51:44,"20,000,000 .. 50,000,000","['CAPCOM Co., Ltd.']","['CAPCOM Co., Ltd.']","['Action', 'Adventure', 'RPG']",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Feb 27, 2025",6999.0,neutral
905,905,Left 4 Dead 2,550,This is a really good game if you love Zombie ...,74,33.550000,2026-03-01 23:18:17,"50,000,000 .. 100,000,000",['Valve'],['Valve'],['Action'],"['windows', 'linux']","['Single-player', 'Multi-player', 'PvP', 'Onli...","Nov 16, 2009",999.0,we need to classify classify
1289,1289,War Thunder,236390,love the game but it pisses me the ♥♥♥♥ off un...,65,224.633333,2024-01-15 07:27:11,"20,000,000 .. 50,000,000",['Gaijin Entertainment'],['Gaijin Network Ltd'],"['Action', 'Massively Multiplayer', 'Simulatio...","['windows', 'mac', 'linux']","['Single-player', 'Multi-player', 'MMO', 'PvP'...","Aug 15, 2013",NaN,negative

In [7]:
from openai import OpenAI
import os
import pandas as pd
import time
from tqdm import tqdm

tqdm.pandas()

client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY", ""),
    base_url="https://openrouter.ai/api/v1"
)

MODEL_NAME = "meta-llama/llama-3.3-70b-instruct:free"
sample_df = data.sample(200, random_state=42).copy()

def normalize_label(label):
    label = str(label).lower().strip()

    if "positive" in label:
        return "positive"
    elif "negative" in label:
        return "negative"
    elif "neutral" in label:
        return "neutral"
    return "neutral"


def get_sentiment(text):
    prompt = f"""
You are an expert classifier for Steam game reviews.

Rules:
- praise, fun, amazing, love, replayability => positive
- lag, crash, bug, boring, trash => negative
- neutral only if there is no opinion

Review:
{text}

Return only:
positive
negative
neutral
"""

    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": "You are a sentiment classifier."},
                {"role": "user", "content": prompt}
            ],
            temperature=0,
            max_tokens=3
        )

        output = response.choices[0].message.content
        time.sleep(0.5)

        return normalize_label(output)

    except Exception as e:
        print("ERROR =>", e)
        return "neutral"

sample_df["label_2"] = (
    sample_df["review_text"]
    .astype(str)
    .progress_apply(get_sentiment)
)

print(sample_df["label_2"].value_counts())

  1%|          | 2/200 [00:03<05:22,  1.63s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

  2%|▏         | 3/200 [00:05<06:13,  1.89s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

  2%|▏         | 4/200 [00:07<06:33,  2.01s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  2%|▎         | 5/200 [00:09<06:23,  1.97s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  3%|▎         | 6/200 [00:11<06:20,  1.96s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  4%|▎         | 7/200 [00:13<06:14,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  4%|▍         | 8/200 [00:15<06:13,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  4%|▍         | 9/200 [00:17<06:14,  1.96s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  5%|▌         | 10/200 [00:19<06:09,  1.95s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  6%|▌         | 11/200 [00:21<06:10,  1.96s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  6%|▌         | 12/200 [00:23<06:07,  1.95s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  6%|▋         | 13/200 [00:25<06:03,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  7%|▋         | 14/200 [00:26<05:52,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  8%|▊         | 15/200 [00:28<05:45,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  8%|▊         | 16/200 [00:30<05:46,  1.89s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  8%|▊         | 17/200 [00:32<05:45,  1.89s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

  9%|▉         | 18/200 [00:34<05:42,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 10%|▉         | 19/200 [00:36<05:39,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 10%|█         | 20/200 [00:38<05:42,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 10%|█         | 21/200 [00:40<05:37,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 11%|█         | 22/200 [00:42<05:40,  1.92s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 12%|█▏        | 23/200 [00:44<05:40,  1.92s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 12%|█▏        | 24/200 [00:46<06:24,  2.18s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831460000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 12%|█▎        | 25/200 [00:49<06:23,  2.19s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 13%|█▎        | 26/200 [00:51<06:18,  2.18s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 14%|█▎        | 27/200 [00:53<06:30,  2.26s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 14%|█▍        | 28/200 [00:55<06:09,  2.15s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 14%|█▍        | 29/200 [00:57<05:59,  2.10s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 15%|█▌        | 30/200 [00:59<05:44,  2.03s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 16%|█▌        | 31/200 [01:01<05:36,  1.99s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 16%|█▌        | 32/200 [01:03<05:23,  1.92s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 16%|█▋        | 33/200 [01:04<05:19,  1.92s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 17%|█▋        | 34/200 [01:06<05:09,  1.86s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 18%|█▊        | 35/200 [01:08<05:01,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 18%|█▊        | 36/200 [01:10<05:03,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 18%|█▊        | 37/200 [01:12<05:13,  1.93s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 19%|█▉        | 38/200 [01:14<05:17,  1.96s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 20%|█▉        | 39/200 [01:16<05:13,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 20%|██        | 40/200 [01:18<05:09,  1.93s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 20%|██        | 41/200 [01:20<05:08,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 21%|██        | 42/200 [01:22<05:02,  1.92s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 22%|██▏       | 43/200 [01:23<04:57,  1.89s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 22%|██▏       | 44/200 [01:25<04:53,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 22%|██▎       | 45/200 [01:27<04:54,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 23%|██▎       | 46/200 [01:29<04:52,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 24%|██▎       | 47/200 [01:31<04:52,  1.91s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 24%|██▍       | 48/200 [01:33<04:49,  1.91s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 24%|██▍       | 49/200 [01:35<04:43,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 25%|██▌       | 50/200 [01:37<04:37,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 26%|██▌       | 51/200 [01:38<04:35,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 26%|██▌       | 52/200 [01:40<04:36,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 26%|██▋       | 53/200 [01:42<04:43,  1.93s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 27%|██▋       | 54/200 [01:44<04:47,  1.97s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 28%|██▊       | 55/200 [01:46<04:45,  1.97s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831520000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 28%|██▊       | 56/200 [01:49<04:52,  2.03s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 28%|██▊       | 57/200 [01:52<05:32,  2.33s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 29%|██▉       | 58/200 [01:54<05:22,  2.27s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 30%|██▉       | 59/200 [01:56<05:02,  2.14s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 30%|███       | 60/200 [01:57<04:49,  2.07s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 30%|███       | 61/200 [01:59<04:38,  2.00s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 31%|███       | 62/200 [02:01<04:36,  2.00s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 32%|███▏      | 63/200 [02:03<04:35,  2.01s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 32%|███▏      | 64/200 [02:05<04:28,  1.98s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 32%|███▎      | 65/200 [02:07<04:17,  1.91s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 33%|███▎      | 66/200 [02:09<04:08,  1.86s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 34%|███▎      | 67/200 [02:11<04:07,  1.86s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 34%|███▍      | 68/200 [02:13<04:11,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 34%|███▍      | 69/200 [02:15<04:10,  1.91s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 35%|███▌      | 70/200 [02:16<04:08,  1.91s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 36%|███▌      | 71/200 [02:18<04:00,  1.86s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 36%|███▌      | 72/200 [02:20<04:01,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 36%|███▋      | 73/200 [02:22<04:03,  1.91s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 37%|███▋      | 74/200 [02:24<04:03,  1.93s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 38%|███▊      | 75/200 [02:26<03:53,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 38%|███▊      | 76/200 [02:28<03:51,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 38%|███▊      | 77/200 [02:29<03:44,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 39%|███▉      | 78/200 [02:31<03:45,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 40%|███▉      | 79/200 [02:33<03:46,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 40%|████      | 80/200 [02:35<03:44,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 40%|████      | 81/200 [02:37<03:45,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 41%|████      | 82/200 [02:39<03:40,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 42%|████▏     | 83/200 [02:41<03:33,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 42%|████▏     | 84/200 [02:42<03:30,  1.81s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 42%|████▎     | 85/200 [02:44<03:27,  1.81s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 43%|████▎     | 86/200 [02:46<03:22,  1.78s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831580000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 44%|████▎     | 87/200 [02:48<03:29,  1.86s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 44%|████▍     | 88/200 [02:50<03:37,  1.95s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 44%|████▍     | 89/200 [02:52<03:50,  2.08s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 45%|████▌     | 90/200 [02:55<04:12,  2.30s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 46%|████▌     | 91/200 [02:57<03:57,  2.18s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 46%|████▌     | 92/200 [03:00<04:01,  2.24s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 46%|████▋     | 93/200 [03:01<03:44,  2.09s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 47%|████▋     | 94/200 [03:03<03:37,  2.05s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 48%|████▊     | 95/200 [03:05<03:32,  2.02s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 48%|████▊     | 96/200 [03:07<03:28,  2.00s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 48%|████▊     | 97/200 [03:09<03:20,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 49%|████▉     | 98/200 [03:11<03:17,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 50%|████▉     | 99/200 [03:13<03:14,  1.92s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 50%|█████     | 100/200 [03:15<03:09,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 50%|█████     | 101/200 [03:16<03:05,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 51%|█████     | 102/200 [03:18<03:06,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 52%|█████▏    | 103/200 [03:20<03:05,  1.91s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 52%|█████▏    | 104/200 [03:22<03:06,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 52%|█████▎    | 105/200 [03:24<03:04,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 53%|█████▎    | 106/200 [03:26<03:00,  1.92s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 54%|█████▎    | 107/200 [03:28<02:55,  1.89s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 54%|█████▍    | 108/200 [03:30<02:55,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 55%|█████▍    | 109/200 [03:32<02:49,  1.86s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 55%|█████▌    | 110/200 [03:34<02:51,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 56%|█████▌    | 111/200 [03:36<02:48,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 56%|█████▌    | 112/200 [03:37<02:44,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 56%|█████▋    | 113/200 [03:39<02:43,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 57%|█████▋    | 114/200 [03:41<02:42,  1.89s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 57%|█████▊    | 115/200 [03:43<02:38,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 58%|█████▊    | 116/200 [03:45<02:33,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 58%|█████▊    | 117/200 [03:47<02:30,  1.81s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831640000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 59%|█████▉    | 118/200 [03:49<02:36,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 60%|█████▉    | 119/200 [03:51<02:41,  2.00s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 60%|██████    | 120/200 [03:53<02:44,  2.06s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 60%|██████    | 121/200 [03:55<02:35,  1.97s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 61%|██████    | 122/200 [03:56<02:26,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 62%|██████▏   | 123/200 [03:59<02:31,  1.97s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 62%|██████▏   | 124/200 [04:01<02:46,  2.19s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 62%|██████▎   | 125/200 [04:03<02:36,  2.09s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 63%|██████▎   | 126/200 [04:05<02:26,  1.99s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 64%|██████▎   | 127/200 [04:07<02:22,  1.96s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 64%|██████▍   | 128/200 [04:09<02:15,  1.89s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 64%|██████▍   | 129/200 [04:10<02:11,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 65%|██████▌   | 130/200 [04:12<02:05,  1.80s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 66%|██████▌   | 131/200 [04:14<02:03,  1.79s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 66%|██████▌   | 132/200 [04:16<02:04,  1.84s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 66%|██████▋   | 133/200 [04:18<02:05,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 67%|██████▋   | 134/200 [04:19<02:01,  1.84s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 68%|██████▊   | 135/200 [04:21<02:00,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 68%|██████▊   | 136/200 [04:23<01:57,  1.84s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 68%|██████▊   | 137/200 [04:25<01:57,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 69%|██████▉   | 138/200 [04:27<01:53,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 70%|██████▉   | 139/200 [04:29<01:51,  1.82s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 70%|███████   | 140/200 [04:30<01:46,  1.78s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 70%|███████   | 141/200 [04:32<01:43,  1.76s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 71%|███████   | 142/200 [04:34<01:45,  1.81s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 72%|███████▏  | 143/200 [04:36<01:42,  1.80s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 72%|███████▏  | 144/200 [04:38<01:44,  1.86s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 72%|███████▎  | 145/200 [04:40<01:45,  1.91s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 73%|███████▎  | 146/200 [04:42<01:43,  1.91s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 74%|███████▎  | 147/200 [04:43<01:39,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 74%|███████▍  | 148/200 [04:45<01:37,  1.87s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831700000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 74%|███████▍  | 149/200 [04:47<01:36,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 75%|███████▌  | 150/200 [04:49<01:37,  1.95s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 76%|███████▌  | 151/200 [04:52<01:40,  2.05s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 76%|███████▌  | 152/200 [04:54<01:38,  2.06s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 76%|███████▋  | 153/200 [04:55<01:31,  1.96s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 77%|███████▋  | 154/200 [04:57<01:31,  1.98s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 78%|███████▊  | 155/200 [04:59<01:26,  1.92s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 78%|███████▊  | 156/200 [05:01<01:23,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 78%|███████▊  | 157/200 [05:03<01:21,  1.90s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 79%|███████▉  | 158/200 [05:06<01:28,  2.10s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 80%|███████▉  | 159/200 [05:07<01:23,  2.04s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 80%|████████  | 160/200 [05:09<01:19,  1.98s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 80%|████████  | 161/200 [05:11<01:16,  1.97s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 81%|████████  | 162/200 [05:13<01:11,  1.89s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 82%|████████▏ | 163/200 [05:15<01:08,  1.84s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 82%|████████▏ | 164/200 [05:17<01:06,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 82%|████████▎ | 165/200 [05:18<01:04,  1.84s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 83%|████████▎ | 166/200 [05:20<01:02,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 84%|████████▎ | 167/200 [05:22<00:59,  1.81s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 84%|████████▍ | 168/200 [05:24<00:57,  1.80s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 84%|████████▍ | 169/200 [05:26<00:55,  1.80s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 85%|████████▌ | 170/200 [05:27<00:54,  1.80s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 86%|████████▌ | 171/200 [05:29<00:50,  1.76s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 86%|████████▌ | 172/200 [05:31<00:50,  1.80s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 86%|████████▋ | 173/200 [05:33<00:49,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 87%|████████▋ | 174/200 [05:35<00:47,  1.84s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 88%|████████▊ | 175/200 [05:36<00:44,  1.80s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 88%|████████▊ | 176/200 [05:38<00:43,  1.82s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 88%|████████▊ | 177/200 [05:40<00:42,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 89%|████████▉ | 178/200 [05:42<00:40,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 90%|████████▉ | 179/200 [05:44<00:38,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 90%|█████████ | 180/200 [05:46<00:36,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831760000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 90%|█████████ | 181/200 [05:48<00:35,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 91%|█████████ | 182/200 [05:50<00:35,  1.97s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 92%|█████████▏| 183/200 [05:52<00:34,  2.00s/it]

ERROR => Error code: 429 - {'error': {'message': 'Provider returned error', 'code': 429, 'metadata': {'raw': 'meta-llama/llama-3.3-70b-instruct:free is temporarily rate-limited upstream. Please retry shortly, or add your own key to accumulate your rate limits: https://openrouter.ai/settings/integrations', 'provider_name': 'Venice', 'is_byok': False}}, 'user_id': 'user_REDACTED'}

 92%|█████████▏| 184/200 [05:54<00:31,  1.98s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 92%|█████████▎| 185/200 [05:56<00:28,  1.89s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 93%|█████████▎| 186/200 [05:57<00:25,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 94%|█████████▎| 187/200 [05:59<00:23,  1.82s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 94%|█████████▍| 188/200 [06:01<00:21,  1.79s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 94%|█████████▍| 189/200 [06:03<00:19,  1.79s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 95%|█████████▌| 190/200 [06:04<00:18,  1.82s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 96%|█████████▌| 191/200 [06:06<00:16,  1.82s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 96%|█████████▌| 192/200 [06:08<00:14,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 96%|█████████▋| 193/200 [06:10<00:13,  1.94s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 97%|█████████▋| 194/200 [06:12<00:11,  1.88s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 98%|█████████▊| 195/200 [06:14<00:09,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 98%|█████████▊| 196/200 [06:15<00:07,  1.80s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 98%|█████████▊| 197/200 [06:17<00:05,  1.85s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

 99%|█████████▉| 198/200 [06:19<00:03,  1.81s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

100%|█████████▉| 199/200 [06:21<00:01,  1.83s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

100%|██████████| 200/200 [06:23<00:00,  1.84s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}

100%|██████████| 200/200 [06:25<00:00,  1.93s/it]

ERROR => Error code: 429 - {'error': {'message': 'Rate limit exceeded: limit_rpm/meta-llama/llama-3.3-70b-instruct/839b2e30-a1b4-4974-b980-3e534b5873b1. High demand for meta-llama/llama-3.3-70b-instruct:free on OpenRouter - limited to 8 requests per minute. Please retry shortly.', 'code': 429, 'metadata': {'headers': {'X-RateLimit-Limit': '8', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1775831820000'}, 'provider_name': None}}, 'user_id': 'user_REDACTED'}
label_2
neutral    200
Name: count, dtype: int64

In [9]:
pip install vaderSentiment

Note: you may need to restart the kernel to use updated packages.Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from vaderSentiment) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from requests->vaderSentiment) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from requests->vaderSentiment) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from requests->vaderSentiment) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\king\appdata\local\programs\python\python311\lib\site-packages (from requests->vaderSentiment) (2025.7.14)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

WARNING: Ignoring invalid distribution ~ip (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (c:\Users\King\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

vader = SentimentIntensityAnalyzer()

def get_sentiment_vader(text):
    score = vader.polarity_scores(str(text))['compound']

    if score >= 0.05:
        return "positive"
    elif score <= -0.05:
        return "negative"
    else:
        return "neutral"


sample_df["label_2"] = sample_df["review_text"].progress_apply(get_sentiment_vader)

100%|██████████| 200/200 [00:00<00:00, 1790.29it/s]

In [64]:
from textblob import TextBlob

def get_sentiment_textblob(text):
    polarity = TextBlob(str(text)).sentiment.polarity

    if polarity > 0.1:
        return "positive"
    elif polarity < -0.1:
        return "negative"
    else:
        return "neutral"
    

sample_df["label_3"] = sample_df["review_text"].progress_apply(get_sentiment_textblob)

100%|██████████| 200/200 [00:00<00:00, 1176.51it/s]

In [ ]:
from tqdm import tqdm
tqdm.pandas()

# sample
sample_df = data.sample(200, random_state=42).copy()

# # Groq (انت عندك function جاهز)
sample_df["label_1"] = sample_df["review_text"].progress_apply(get_sentiment_groq)

# VADER


# TextBlob


sample_df.head()

100%|██████████| 200/200 [00:14<00:00, 13.79it/s]
100%|██████████| 200/200 [00:00<00:00, 1217.36it/s]
100%|██████████| 200/200 [00:00<00:00, 4807.75it/s]

,Unnamed: 0,game_name,app_id,review_text,review_length,hours_played,review_date,owners,developers,publishers,genres,platforms,categories,release_date,price,label_1,label_2,label_3
1860,1860,Path of Exile 2,2694490,`,1,10.600000,2026-02-26 23:50:27,"20,000,000 .. 50,000,000",['Grinding Gear Games'],['Grinding Gear Games'],"['Action', 'Adventure', 'Massively Multiplayer...",['windows'],"['Single-player', 'Multi-player', 'MMO', 'Co-o...","Dec 6, 2024",2999.0,"i'm ready to annotate the review. however, it ...",neutral,neutral
353,353,Palworld,1623730,incredibly fun and great replayability (i thin...,79,92.016667,2026-02-28 14:33:41,"50,000,000 .. 100,000,000",['Pocketpair'],['Pocketpair'],"['Action', 'Adventure', 'Indie', 'RPG', 'Early...",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Jan 18, 2024",2999.0,neutral,positive,positive
1333,1333,Monster Hunter Wilds,2246340,I Monster my Hunter till I Wilds,32,113.883333,2026-03-01 10:51:44,"20,000,000 .. 50,000,000","['CAPCOM Co., Ltd.']","['CAPCOM Co., Ltd.']","['Action', 'Adventure', 'RPG']",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Feb 27, 2025",6999.0,neutral,neutral,neutral
905,905,Left 4 Dead 2,550,This is a really good game if you love Zombie ...,74,33.550000,2026-03-01 23:18:17,"50,000,000 .. 100,000,000",['Valve'],['Valve'],['Action'],"['windows', 'linux']","['Single-player', 'Multi-player', 'PvP', 'Onli...","Nov 16, 2009",999.0,neutral,positive,positive
1289,1289,War Thunder,236390,love the game but it pisses me the ♥♥♥♥ off un...,65,224.633333,2024-01-15 07:27:11,"20,000,000 .. 50,000,000",['Gaijin Entertainment'],['Gaijin Network Ltd'],"['Action', 'Massively Multiplayer', 'Simulatio...","['windows', 'mac', 'linux']","['Single-player', 'Multi-player', 'MMO', 'PvP'...","Aug 15, 2013",NaN,neutral,positive,negative

In [65]:
sample_df

,Unnamed: 0,game_name,app_id,review_text,review_length,hours_played,review_date,owners,developers,publishers,genres,platforms,categories,release_date,price,label_1,label_2,label_3
1860,1860,Path of Exile 2,2694490,`,1,10.600000,2026-02-26 23:50:27,"20,000,000 .. 50,000,000",['Grinding Gear Games'],['Grinding Gear Games'],"['Action', 'Adventure', 'Massively Multiplayer...",['windows'],"['Single-player', 'Multi-player', 'MMO', 'Co-o...","Dec 6, 2024",2999.0,neutral,neutral,neutral
353,353,Palworld,1623730,incredibly fun and great replayability (i thin...,79,92.016667,2026-02-28 14:33:41,"50,000,000 .. 100,000,000",['Pocketpair'],['Pocketpair'],"['Action', 'Adventure', 'Indie', 'RPG', 'Early...",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Jan 18, 2024",2999.0,positive,positive,positive
1333,1333,Monster Hunter Wilds,2246340,I Monster my Hunter till I Wilds,32,113.883333,2026-03-01 10:51:44,"20,000,000 .. 50,000,000","['CAPCOM Co., Ltd.']","['CAPCOM Co., Ltd.']","['Action', 'Adventure', 'RPG']",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Feb 27, 2025",6999.0,negative,neutral,neutral
905,905,Left 4 Dead 2,550,This is a really good game if you love Zombie ...,74,33.550000,2026-03-01 23:18:17,"50,000,000 .. 100,000,000",['Valve'],['Valve'],['Action'],"['windows', 'linux']","['Single-player', 'Multi-player', 'PvP', 'Onli...","Nov 16, 2009",999.0,positive,positive,positive
1289,1289,War Thunder,236390,love the game but it pisses me the ♥♥♥♥ off un...,65,224.633333,2024-01-15 07:27:11,"20,000,000 .. 50,000,000",['Gaijin Entertainment'],['Gaijin Network Ltd'],"['Action', 'Massively Multiplayer', 'Simulatio...","['windows', 'mac', 'linux']","['Single-player', 'Multi-player', 'MMO', 'PvP'...","Aug 15, 2013",NaN,negative,positive,negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,462,Team Fortress 2,440,the OG. The big chunga. This was one of the bi...,94,103.883333,2026-02-20 16:00:58,"50,000,000 .. 100,000,000",['Valve'],['Valve'],"['Action', 'Free To Play']","['windows', 'linux']","['Multi-player', 'Cross-Platform Multiplayer',...","Oct 10, 2007",NaN,positive,neutral,neutral
1105,1105,Lost Ark,1599340,I'm so grateful I quit playing in June of 2022...,319,924.116667,2026-02-22 04:17:29,"50,000,000 .. 100,000,000",['Smilegate RPG'],['Amazon Game Studios'],"['Action', 'Adventure', 'Massively Multiplayer...",['windows'],"['Single-player', 'Multi-player', 'MMO', 'PvP'...","Feb 11, 2022",NaN,negative,positive,positive
855,855,Grand Theft Auto V Legacy,271590,best game,9,31.683333,2026-03-01 07:10:12,"50,000,000 .. 100,000,000",['Rockstar North'],['Rockstar Games'],"['Action', 'Adventure']",['windows'],"['Single-player', 'Multi-player', 'PvP', 'Onli...","Apr 13, 2015",NaN,positive,positive,positive
693,693,New World: Aeternum,1063730,I started a few times over since the story cha...,592,1342.783333,2026-02-08 09:09:30,"50,000,000 .. 100,000,000",['Amazon Game Studios'],['Amazon Game Studios'],"['Action', 'Adventure', 'Massively Multiplayer...",['windows'],"['Multi-player', 'MMO', 'PvP', 'Online PvP', '...","Sep 28, 2021",NaN,negative,negative,neutral
1551,1551,Warframe,230410,"at the very end, when i stop playing any and a...",96,2656.066667,2023-12-03 17:33:24,"20,000,000 .. 50,000,000",['Digital Extremes'],['Digital Extremes'],"['Action', 'RPG', 'Free To Play']",['windows'],"['Single-player', 'Multi-player', 'Co-op', 'On...","Mar 25, 2013",NaN,positive,negative,neutral

In [66]:
from statsmodels.stats.inter_rater import fleiss_kappa
import numpy as np
import pandas as pd

# labels dataframe
df = sample_df[["label_1", "label_2", "label_3"]]

def to_fleiss(row):
    return [
        (row == "positive").sum(),
        (row == "negative").sum(),
        (row == "neutral").sum()
    ]

fleiss_matrix = df.apply(to_fleiss, axis=1).tolist()


fleiss_matrix = np.array(fleiss_matrix)

score = fleiss_kappa(fleiss_matrix)

print("Fleiss Kappa =", score)

Fleiss Kappa = 0.41515214129780514

In [69]:
sample_df.to_csv(r"D:\\ground_truth.CSV")